permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Michaela Robinson"
  font_url: "https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,500,500i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap"
