permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Michaela Robinson"
  font_url: "https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,300;0,400;0,700;0,900;1,400;1,700;1,900&display=swap" rel="stylesheet">"
  description: |
    A website showcasing the works of Michaela Robinson, graphic designer from Ottawa.
  rationales:
    typefaces.primary: |
      Raleway was selected for easy, clear readability. This font has clean lines and rounded edges and a large x-height which represents the brand identity as friendly but professional.
    typefaces.secondary: |
      Garamond was selected for the secondary typeface to compliment and contrast Montserrat. This typeface serves as body copy and subtitles for this webpage.
    colors.primary: |
      The primary colour is a clean, relaxing blue which serves as the main colour users will notice throughout the website.
    colors.primary: |
      The secondary colour is a warm toned peach pink which will provide contrast to the blue.
    colors.accent: |
      The accent colour is a warm toned yellow which provides contrast to both the pink and the blue colours.
