permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Michaela Robinson"
  font_url: "https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,500,500i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap"
  description: |
    A website showcasing the works of Michaela Robinson, graphic designer from Ottawa.
  rationales:
    typefaces.primary: |
      Montserrat was selected for easy, clear readability. This font has clean lines and rounded edges and a large x-height which represents the brand identity as friendly but professional.
    typefaces.secondary: |
      Garamond was selected for the secondary typeface to compliment and contrast Montserrat. This typeface serves as body copy and subtitles for this webpage.
    colors.primary: |
      The primary colour is a clean, relaxing blue which serves as the main colour users will notice throughout the website.
    colors.primary: |
      The secondary colour is a warm toned peach pink which will provide contrast to the blue.
    colors.accent: |
      The accent colour is a warm toned yellow which provides contrast to both the pink and the blue colours.
