permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Michaela Robinson"
  font_url: "https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,500,500i,600,600i,700,700i|Montserrat:100,100i,200,200i,300,300i,400,500,500i,600,600i,700,700i,800,800i&display=swap"
