title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    fields:
      - name: text
        type: string
        example: "Click here"
      - name: url
        type: url
        example: "/Click here/"
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
  ghost:
    fields:
      - name: text
        type: string
        example: "Click here"
      - name: url
        type: url
        example: "/Click here/"
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
    background: "--color-primary-light"
  light:
    fields:
      - name: text
        type: string
        example: "Click here"
      - name: url
        type: url
        example: "/Click here"
    title: "Light"
    description: |
      The light button is to be used when the background is too dark for the default button and too light for the ghost button.
