title: "Cards"
description: |
  Cards should be used to showcase images, call to actions and showcase information.

patterns:
  photo-card:
    fields:
      - name: image
        type: string
        example: "300x600placeholder.png"
    title: "Work Category"
    description: |
      This type of card is used as a link to view a work in more detail.
  photo-text-card:
    fields:
      - name: image
        type: string
        example: "720x720placeholder.jpg"
      - name: heading
        type: string
        example: "About me"
      - name: text
        type: string
        example: "I'm a graphic designer from Ottawa, Canada. I’m terrible at math. Early on, I knew I would never be someone who works with numbers, but I was promised there’s no way to make a living being creative. I made a promise to myself to love what I do for a living. Design for me, is a way of life, full of colour. I started my education using paint, brushes and pencils and ended with a computer and a mouse, proving that I can in fact have a career from being creative and I can just google my math problems."
    description: |
      This type of card is used as a way to display and image with related text.
    text-photo-card:
      fields:
        - name: image
          type: string
          example: "720x720placeholder.jpg"
        - name: heading
          type: string
          example: "Honey Bunches of Oats Redesign"
        - name: text
          type: string
          example: "This assignment is a print work which involved redesigning the Honey Bunches of Oats cereal box to create a more dynamic shape and way of showcasing the product. The redesign demonstrates my ability to think in three dimensional forms while working in one dimensional form on the computer. This showcases my ability to bring a thought or design to life in a real tangible way and my ability to work through difficulties to figure out a viable solution."
      description: |
        This type of card is used as a way to display text on the left side of an image.
