title: "Banners"
description: |
  Banners should be used as the first main image on each page.

patterns:
  main-banner:
    fields:
      - name: heading
        type: string
        example: "Graphic Designer"
      - name: text
        type: string
        example: "from Ottawa, Canada"
      - name: image
        type: string
        example: "main-banner.jpg"
      - name: button_text
        type: string
        example: "Button"
      - name: button_url
        type: url
        example: "//"
    title: "Main Banner"
    description: |
      This type of banner is used as the first element on each page after the navigation.
  portfolio-banner:
    fields:
      - name: image
        type: string
        example: "main-banner.jpg"
    title: "Portfolio Banner"
    description: |
      This type of banner is used as the first image for each individual portfolio piece. This image is showcasing the best image of the portfolio piece and is used to grab the viewer's attention. This banner is used when there is no text to be used on a banner, only the image.
