title: "Banners"
description: |
  Banners should be used as the first main image on each page.

patterns:
  main-banner:
    fields:
      - name: heading
        type: string
        example: "Graphic Designer"
      - name: text
        type: string
        example: "from Ottawa, Canada"
      - name: image
        type: string
        example: "banner-placeholder-03.jpg"
      - name: button_text
        type: string
        example: "Button"
      - name: button_url
        type: url
        example: "//"
    title: "Main Banner"
    description: |
      This type of banner is used as the first element on each page after the navigation.
